### ISSUE TITLE
String "\" is replaced by ""

### ISSUE THREAD

**Issue by Toilal** [sayanarijit/expandvars#1]
```
>>> import expandvars
>>> expandvars.expandvars('D:\\test')
'D:test'
```

**Comment by Toilal** [comment]
My current workaround is too double them, but it's not so obvious.

```
expandvars.expandvars('D:\\test'.replace('\\', '\\\\'))
```

**Comment by sayanarijit** [comment]
I didn't test it on Windows. However,
I think you should use unix style paths. `d:/test` or even `/d/test` might work. (Works on git bash)

**Comment by Toilal** [comment]
I have included expandvars in an application that produces backslashes for paths, I can't really change this. Would you consider a pull request to enhance the escaping behavior ? I think it should not drop the backslash if the following character as nothing "special" ?

**Comment by sayanarijit** [comment]
I don't mind, but that would mean adding Windows compatibility. The problem is that supporting windows is really difficult. Common open-source tools like travis can run tests on Linux only. Although may try and propose a solution that may help us deal with continuous testing on windows without putting much effort.

**Comment by sayanarijit** [comment]
The escaping behaviour is taken from gnu bash. I don't think it would be solved simply adding another backslash. We need to consider unix flatform also. So if it's possible to use an in-built compatibility library, it may solve the problem but then again, we need a test suit to maintain this compatibility in future versions also.

**Comment by sayanarijit** [comment]
Okay I see your point.

```
katana ➜  ~ x='D:\\test'
katana ➜  ~ echo $x
D:\test
```
Right sorry... This needs fix.

**Comment by sayanarijit** [comment]
@Toilal it would be great if you could raise a PR. You might need to update the test cases here:
https://github.com/sayanarijit/expandvars/blob/master/tests/test_expandvars.py#L87

**Comment by sayanarijit** [comment]
Opps. The story is even deeper. 😩 

```
katana ➜  expandvars git:(master) x="D:\\test"
katana ➜  expandvars git:(master) echo $x
D:	est
```
I have been considering double quoted values in Unix. Which means "evaluate the special symbols". And in bash, `\t` is evaluated to tab (`	`).

**Comment by sayanarijit** [comment]
If it's not a special symbol, it should work as you suggested.

```
katana ➜  expandvars git:(master) x="D:\\zest"
katana ➜  expandvars git:(master) echo $x
D:\zest
```

**Comment by sayanarijit** [comment]
Hmm... Adding special symbol support will take it to another direction than just expanding env vars.
Ref: https://docstore.mik.ua/orelly/unix/upt/ch08_19.htm

We'll ignore special symbols and expand `D:\test` into `D:\test` as you suggested.

**Comment by sayanarijit** [comment]
Anyway, it doesn't and can't follow bash strictly.

**Comment by sayanarijit** [comment]
Okay I completely forgot I have been using zsh, not bash 😄 
```
bash-3.2$ x="d:\\test"
bash-3.2$ echo $x
d:\test
```

**Comment by sayanarijit** [comment]
@Toilal please feel free to [directly ping me on slack](https://pyslackers.com/slack/) if you need any help fixing this.
