### ISSUE TITLE
Feature request: support raising an exception on missing env-vars

### ISSUE THREAD

**Issue by iMoses** [sayanarijit/expandvars#15]
This tiny feature is really missing from the original `os.path.expendvars` and when used with config files that's a big headache.
It'd be nice if you can add support for throwing errors instead of falling to an empty string, a boolean kwarg which can be set and is disabled by default.
I can have a PR ready if you're okay with this.

**Comment by sayanarijit** [comment]
Hi, you can do this with the `${VAR:?}` or `${VAR?}` syntax similar to bash.

Examples: https://github.com/sayanarijit/expandvars/blob/master/tests/test_expandvars.py#L144

**Comment by iMoses** [comment]
oh, nice! i didn't notice that..
yeah, looks like this solves my problem :)

**Comment by mnieber** [comment]
That's a nice solution but it has the downside that it's lenient by default. I would like to have the option of using strictness by default. For example, imagine a use case where we are parsing a configuration file created by an end user and we want them to use only environment variables that are defined. In that case it would be great if I could call `expanded_config = expandvars(config_file_contents, strict=True)`

**Comment by sayanarijit** [comment]
Hi @mnieber, yes that's a valid point. Thanks for pointing this out. Do you think #17 will solve your use case?

**Comment by mnieber** [comment]
Yes, that should solve it!

**Comment by sayanarijit** [comment]
Published v0.6.0 with the new feature.
