### ISSUE TITLE
Make variable character `$` customizable

### ISSUE THREAD

**Issue by frthjf** [sayanarijit/expandvars#26]
This might be out of scope for this package, but I think it would be very useful if the package could also be to Unix style expression with custom variable characters, for example:
```
my_secret_access_code = "%{ACCESS_CODE:-default_access_code}"
my_important_variable = "%{IMPORTANT_VARIABLE:?}"
my_updated_path = %PATH:%HOME/.bin"
```
```python
expandvars(file, varchar="%")
```
In particular in combination with #25, it would allow to use the package to parse fully custom variable specifications.

**Comment by sayanarijit** [comment]
Based on the use cases I think both are pretty useful to have.

However, to keep things simple, I'd like to keep the `expandvars()` API limited to only the bash specific options (e.g. `nounset`) and behavior and expose a new function `expand()` to allow for more control / customization.


```python
def expand(vars_, nounset=False, environ=os.environ, var_symbol="$"):
   ...

def expandvars(vars_, nounset=False):
    expand(vars_, nounset=nounset)
```

@frthjf how does it look?

**Comment by frthjf** [comment]
Hi @sayanarijit, yes, that makes a lot of sense. Thanks! (Happy to prepare a PR for this if needed)

**Comment by sayanarijit** [comment]
Sure... A PR would be great.

**Comment by sayanarijit** [comment]
Merged: https://github.com/sayanarijit/expandvars/pull/30

**Comment by frthjf** [comment]
Awesome, thanks @sayanarijit :+1:
