### ISSUE TITLE
Bug with expansion inside ":+" expansion?

### ISSUE THREAD

**Issue by YKdvd** [sayanarijit/expandvars#49]
The following example of parameter expansion within another expansion works in bash (Ubuntu and MacOS, also zsh on the latter):
```bash
export FAKE_PATH=
echo ${FAKE_PATH:+${FAKE_PATH};}/mongoose
export FAKE_PATH=/wombat
echo ${FAKE_PATH:+${FAKE_PATH};}/mongoose
```
The intent is to only append the ";" character if "FAKE_BATH" is already set, to avoid getting ";/mongoose" when it isn't.  The result is as expected:
```
/mongoose
/wombat;/mongoose
```
But Python (3.9) code that should be the equivalent for expandvars:
```python
import expandvars
s= r"${FAKE_PATH:+${FAKE_PATH};}/mongoose"
#print(s)
env = {}
result = expandvars.expand(s, environ=env)
print("%s"%(result))
env["FAKE_PATH"] = "/wombat"
result = expandvars.expand(s, environ=private)
print("%s"%(result))
```
fails, and produces:
```
;}/mongoose
${FAKE_PATH;}/mongoose
```
I'm guessing the expandvars parser can't handle this otherwise bash-acceptable syntax with an expansion inside an expansion?

**Comment by sayanarijit** [comment]
Thanks for reporting.

https://github.com/sayanarijit/expandvars/pull/50 should fix it. @YKdvd could you please confirm?

**Comment by sayanarijit** [comment]
Minor fix: https://github.com/sayanarijit/expandvars/pull/51

**Comment by sayanarijit** [comment]
Also https://github.com/sayanarijit/expandvars/pull/52
