### ISSUE TITLE
expandvars 0.8.0 broke dollar sign escaping after an advanced substitution 

### ISSUE THREAD

**Issue by mark7-bell** [sayanarijit/expandvars#53]
The following example correctly displays `"$foo"` with expandvars 0.7.0, but incorrectly displays `None` with expandvars 0.8.0:
```
from expandvars import expandvars
from yaml import load, SafeLoader


foo = '''
path: ${PATH:=bar}
test: \$foo
'''

print(load(expandvars(foo), Loader=SafeLoader))
```

Example 0.7.0 good output:
```
{'path': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'test': '$foo'}
```

Example 0.8.0 bad output:
```
{'path': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'test': None}
```

The problem appears to be related to the new recursive calls in `expand_advanced`.

**Comment by sayanarijit** [comment]
My bad... I think it's time to rewrite the whole thing using actual syntax tree parsing logic.

**Comment by sayanarijit** [comment]
For now, let's use workaround.
