### ISSUE TITLE
Conda Forge Package

### ISSUE THREAD

**Issue by tierriminator** [sayanarijit/expandvars#55]
I quite like this library and want to use it in a project where I provide a conda recipe.
Would you mind publishing the package via conda-forge?
This should be quite easy with [Grayskull](https://conda-forge.org/blog/posts/2020-03-05-grayskull/).

**Comment by sayanarijit** [comment]
Hi, I'm not very involved with conda, hence testing and maintaining a conda release would be a friction for me. If conda doesn't require the maintainer to also be the auther, you can maintain the conda release. I can help you with this repo, and will merge prs for the support files, if any. You may also fork this if you feel like that's the best way.

The pure python release is pretty much feature complete. I'm currently working on a Rust library to implement a proper parser, and plan to use that as the core for this Python library in the future. But I don't have a timeline for that.

**Comment by tierriminator** [comment]
Hi
I would suggest then that I'll submit a simple recipe with Grayscull on conda-forge with your permission.
Since you are already publishing on PyPI, it should be quite easy to create and to maintain.

**Comment by sayanarijit** [comment]
Sounds good. Thank you.
