### ISSUE TITLE
Release 0.11.0 is not tagged in git

### ISSUE THREAD

**Issue by g-v-egidy** [sayanarijit/expandvars#60]
Hi,

I have seen that you seem to have released version 0.11.0 of this project. At least the comments in the checkins suggest that. 

But the releases 0.10.0 and 0.11.0 don't seem to be tagged in git. This makes it hard for me (and I guess other users too) to download and package these releases in exactly the way they were released. 

This is important when you don't wan't to rely on pypi and want to be able to reproduce the builds exactly from source yourself.

Please tag these releases in git. Thank you.

**Comment by sayanarijit** [comment]
Thanks for bringing this up. Pushed [v0.11.0](https://github.com/sayanarijit/expandvars/releases/tag/v0.11.0).

**Comment by g-v-egidy** [comment]
Thank you for fixing this so fast
